### ISSUE TITLE
OS X build not running

### ISSUE THREAD

**Issue by rpkilby** [rpkilby/tox-venv#11]
Hi @ryanhiebert - it's not immediately clear to me what's happening, but it looks like I might have some misconfiguration that's preventing tox-travis from picking up the correct test env for os x builds. Any ideas? 

Latest OS X build: https://travis-ci.org/tox-dev/tox-venv/jobs/363364933

**Comment by ryanhiebert** [comment]
Your setup seems pretty sane, so I'm shooting in the dark a bit, but what about:

* Add a `python3.6` symlink as well as the `python3` symlink. Tox uses the longer version, IIRC.
* After homebrew runs, it gives an error on line 2325: `rm: /usr/local/bin/python: No such file or directory`
* It's odd to see the ruby, rvm, and yarn stuff in the build log, since this run is configured as `language: generic`.
* The error removing the `python` symlink gets me wondering if `tox` is somehow running under a system version of Python instead of the one you installed. Unless that's Python 2.6, I still don't see why that would cause it not to run, but it may be something worth checking on.

That's all I got from reading the logs and the current configuration, maybe something there will help it make sense.

**Comment by rpkilby** [comment]
Hey - thanks for the help/digging through the logs.

> It's odd to see the ruby, rvm, and yarn stuff in the build log

That output should be coming from the `.travis-osx` script (copied from tox).

> The error removing the python symlink gets me wondering if tox is somehow running under a system version of Python instead of the one you installed.

My guess is that `/usr/local/bin/python` is the location of the python binary in older version of OS X, but has since moved. The script `.travis-osx` script is probably outdated.

----

Either way, it turns out that I had misconfigured tox-travis by not providing an os mapping. I don't usually test against OS X and forgot it was necessary. Fixed in #12.

**Comment by ryanhiebert** [comment]
Oh, OK, that makes sense. The `python` auto-key would not be used, because the `TRAVIS_PYTHON_VERSION` isn't set. Setting the `os` key is probably the cleanest, I suppose that another option would be to manually set `TRAVIS_PYTHON_VERSION` in the `.travis.yml` for this job as well. Your fix seems a bit cleaner to me.
